name: terraform-k6

on:
  workflow_run:
    workflows: [ "pages-build-deployment" ]
    types:
      - completed

jobs:
  terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      TF_VAR_gc_access_policy_token: ${{ secrets.GC_ACCESS_POLICY_TOKEN }}

    outputs:
      k6_project_id: ${{ steps.extract.outputs.k6_project_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init (Cloud)
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - id: extract
        name: Extract the 'k6_project_id'
        run: |
          ID=$(terraform output -raw k6_project_id)
          echo "k6_project_id=$ID" >> $GITHUB_OUTPUT

  k6:
    needs: terraform
    runs-on: ubuntu-latest

    env:
      K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
      K6_CLOUD_PROJECT_ID: ${{ needs.terraform.outputs.k6_project_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up k6
        uses: grafana/setup-k6-action@v1
        with:
          browser: true

      - name: Run k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: |
            ./*.js
          cloud-run-locally: false
          cloud-comment-on-pr: true